
name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk+fx
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build package
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging  && cp target/*.exe staging
      - name: Save package
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging