
name: Java CI with Maven

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.202
          java-package: jdk+fx
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: \%userprofile%/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build package
        run: mvn -B package --file pom.xml
      - name: Create installer
        uses: joncloud/makensis-action@v2.0
        with:
          script-file: tools/install.nsi
          arguments: /V4
      - name: Isolate binaries
        run: |
          mkdir staging
          del target\original*.jar
          copy LICENSE.txt staging
          copy target\*.jar staging
          copy target\*.exe staging
      - name: Save package
        uses: actions/upload-artifact@v2
        with:
          name: dist-windows
          path: staging

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.202
          java-package: jdk+fx
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install macOS build dependency
        run: sudo apt-get install -y genisoimage
      - name: Build package
        run: mvn -B package --file pom.xml
      - name: Isolate binaries
        run: |
          mkdir staging
          cp target/*.dmg staging
      - name: Save package
        uses: actions/upload-artifact@v2
        with:
          name: dist-mac
          path: staging

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-windows
          path: target-windows
      - name: Download Mac artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-mac
          path: target-mac
      - name: Push release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            target-windows/LICENSE.txt
            target-windows/*.jar
            target-windows/*.exe
            target-mac/*.dmg